name: Swift

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Available devices
        run: xcrun simctl list devicetypes

      - name: Run tests
        run: xcodebuild test -scheme PAX -destination 'platform=iOS Simulator,name=iPhone 14 Pro'